version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user_root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: rahncc
    volumes:
      - /root/docker/wordpress/data:/var/www/html
      - /root/docker/wordpress/data/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: rahncc
      MYSQL_USER: user_root
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: helloworldmysqql
    volumes:
      - /root/docker/wordpress/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3500:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD : helloworldmysqql
    volumes:
      - /root/docker/wordpress/phpmyadmin:/var/www/html/phpmyadmin 
